# Generated by Django 4.2.7 on 2023-11-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_size_color_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
        migrations.RemoveField(
            model_name='color',
            name='products',
        ),
        migrations.RemoveField(
            model_name='size',
            name='products',
        ),
    ]
