# Generated by Django 4.2.7 on 2023-11-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_color_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
    ]
