version: "3.11"

services:
  backend:
    container_name: django-container
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django_db
    ports:
      - '5432:5432'
    volumes:
      - django_db:/var/lib/postgresql
    restart: always

volumes:
  django_db:
